package com.example.ienabuna

object IeNaBuNaData {
    private val acehFoodNames = arrayOf(
        "Asam Keueng",
        "Ayam Tangkap",
        "Boh Rom-Rom",
        "Kuah Pliek",
        "Kue Adee",
        "Martabak Aceh",
        "Mie Aceh",
        "Mie Jalak",
        "Roti Jala",
        "Rujak Aceh",
        "Sate Matang",
        "Sie Itek",
        "Sie Kameng",
        "Timphan",
        "Keumamah")

    private val acehFoodDetails = arrayOf(
        "Asam keueng merupakan salah satu masakan khas Aceh yang tampilan dan rasanya sebenarnya mirip-mirip dengan gulai asam padeh dari Padang. Bedanya pada asam padeh, komposisi cabai merahnya cukup banyak sehingga tampilan kuahnya tampak merah membara. Sementara asam keueng walau bercita rasa pedas dan asam juga namun menggunakan porsi kunyit lebih banyak sehingga warnanya terlihat kekuningan. \nPerbedaan lainnya adalah pada jenis asam yang digunakan, umumnya asam padeh menggunakan asam kandis yang terbuat dari buah tanaman Garcinia xanthochymus yang dikeringkan, sedangkan asam sunti terbuat dari buah tanaman belimbing wuluh (Averrhoa bilimbi). \n\nDari segi rasa maka asam sunti memberikan rasa asam yang lebih lembut, unik dan tidak setajam asam pada asam kandis. Saya sendiri lebih suka rasa asam yang dihasilkan oleh asam sunti, karena walaupun kita masukkan cukup banyak ke dalam masakan tidak secara drastis membuat rasa masakan menjadi terlalu kecut. Selain penggunaan asam sunti, masakan asam keueng juga menggunakan daun rempah bernama daun kari atau salam koja. Daun ini memberikan aroma khas kari yang lembut membuat masakan asam keueng anda menjadi lebih spesial.",
        "Ayam Tangkap adalah masakan khas Aceh, yang terbuat dari ayam yang digoreng dengan bumbu dan rempah-rempah khas. Saat disajikan Ayam ini tampak unik, karena banyak Daun pandan yang ikut tergoreng dan disajikan di piring. Ayam Tangkap disajikan dengan daun-daunan seperti daun temurui dan daun pandan yang dirajang kasar serta digoreng renyah. Mencicipi daun renyah mungkin akan terasa aneh, namun apabila dipadukan dengan ayam goreng, menghasilkan cita rasa yang khas dan nikmat. \n\nRasa yang khas itulah yang menjadi keistimewaan dari menu Ayam ini. Bagi yang baru pertama kali menikmati masakan Ayam Tangkap ini, biasanya akan merasakan sensasi rasa yang berbeda dengan masakan ayam lainnya. Rasa daging ayam yang gurih dipadukan dengan daun temurui dan daun pandan yang renyah tentu memberikan cita rasa yang khas pada makanan tradisional satu ini. Menikmati menu Ayam yang satu ini sangat cocok disajikan saat masih hangat dipadukan dengan nasi hangat juga. Wah sungguh nikmat sekali. \n\nPembuatan ayam tangkap terbilang mudah. Sebelum dimasak, ayam diberi bumbu terlebih dahulu yakni bawang putih, lada, garam, kemiri dan jahe. Setelah ayam dibumbui secara merata barulah ayam digoreng selama 5 sampai 10 menit. Kemudian jangan lupa masukan pula dedaunan yang akan disajikan bersama ayam sehingga rasa rempah dedaunan turut meresap ke dalam daging ayam. Dedaunan yang dipakai tersebut diantaranya daun kari, potongan daun pandan, dan salam koja. Setelah itu, tinggal tunggu saja ayam hingga matang secara merata. Setelah ayam matang, sajikan di piring bersamaan dengan dedaunan tadi dan jadilah ayam tangkap yang nikmat dan menggugah selera makan. ",
        "Kue berbentuk bola pimpong ini memiliki nama yang unik; boh rom-rom. Kudapan sejenis onde-onde yang dilumuri kelapa parut ini paling khas di Aceh saat bulan puasa. Hampir semua rumah menyediakannya. Rasanya yang kenyal dan manis serta bentuknya yang imut, membuat boh rom-rom digemari semua usia. Kerap menjadi camilan wajib bagi warga Bumi Serambi Mekkah saat berbuka puasa. \n\nMembuat boh rom-rom tergolong mudah. Bahan utamanya tepung ketan, kemudian dicampur garam sedikit dan tuangkan air panas secukupnya. Aduk merata hingga jadi adonan. Agar lebih beraroma dan berwarna, tambahkan sedikit sari daun pandan. \n\nAdonan yang sudah jadi kemudian di-comot seukuran telur puyuh, lubangi sedikit di tengahnya, masukkan gula pasir atau potongan gula aren. Selanjutnya tutup lagi dan bulatkan dengan telapak tangan hingga berbentuk bola kecil. \n\nLangkah berikutnya adalah merebusnya hingga matang, kemudian lumuri dengan kelapa parut yang sudah dicampur sedikit gula. Boh rom-rom pun siap disajikan. Lebih nikmat jika disantap hangat-hangat. \n\nMakan boh rom-rom memang memiliki sensasi tersendiri. Saat camilan imut ini terkena gigitan, isi di dalamnya bisa muncrat keluar. Jadi bagusnya boh rom-rom dimasukkan sekalian ke mulut, jangan digigit setengah-setengah.",
        "Kuah Pliek U adalah makanan tradisional sejenis masakan bersantan yang khas dari daerah Aceh. Makanan satu ini sekilas hampir mirip dengan Gulai hanya saja isinya berupa sayuran dan kuahnya terbuat dari bahan khusus. Kuah Pliek U merupakan salah satu makanan tradisional yang cukup terkenal di daerah Aceh, khususnya di daerah pesisir timur Aceh. \n\nSelain dikonsumsi sehari-hari, Kuah Pliek U juga sering disajikan pada acara-acara tertentu dan menjadi salah satu menu special yang digemari oleh warga di sana. \n\nKuah Pliek U ini terbuat dari bahan utama seperti buah nangka muda, papaya muda, daun melinjo, kacang panjang, kacang tanah, buah melinjo dan pliek u. Selain itu ada juga yang menambahkan beberapa bahan seperti rebung, daun papaya, daun singkong, udang kecil dan lain-lain. Sedangkan untuk bumbu yang digunakan biasanya terdiri dari ketumbar, cabe,bawang merah, bawang putih, dan bumbu rempah lainnya.\n\nDalam proses pengolahannya, bumbu tersebut dihaluskan terlebih dahulu. Sedangkan bahan yang bertekstur keras seperti buah melinjo dan kacang tanah harus direbus terlebih dahulu hingga empuk. Setelah semuanya siap, bumbu serta sayuran dicampur dan diaduk-aduk hingga merata. Kemudian bahan yang sudah dicampur dengan bumbu tadi dimasukan ke dalam belangga (wajan), lalu diberi air santan dan direbus hingga matang.Kuah Pliek U ini biasanya disajikan bersama dengan nasi hangat. Untuk menu tambahan biasanya juga disantap bersama dengan ikan asin.",
        "Kue adee merupakan kue oleh oleh khas Aceh yg berasal dari Aceh, nama lain kue ade adalah kue bingkang. Kue ini memiliki tekstur yang lembut dan cocok untuk dijadikan camilan saat bersantai bahkan menu pembuka saat buka puasa. bahkan di salah satu wilayah aceh Kue ini sudah menjadi oleh-oleh khas aceh bawaan yan bisa di dapatkan di wilayah Pidie Jaya. \n\nKue yang di bakar di oven ini memiliki dua rasa, yaitu rasa tepung dan ubi. Kedua-duanya memiliki rasa yang sama-sama enak dan legit. Aroma bawang goreng dan rasa pandan di tambah dengan tekstur lembut dan kenyal benar-benar menggugah selera. Harga kue Adee sendiri bervariasi tergantung ukuran, karena ada yang kecil dan besar. Hampir semua kios harganya sama, untuk yang kecil sekitar Rp. 16 ribuan, dan yang besar berkisar Rp. 25 ribuan. Kini kue Adee khas Pidie Jaya ini sangat mudah untuk Anda peroleh. Anda tidak perlu jauh-jauh ke Kabupaten Pidie Jaya, karena di Aceh Besar dan di Kota Banda Aceh bisa Anda dapatkan. Selain ada cabang khusus dari Meureudu di Banda Aceh dan Aceh besar, banyak juga kue Adee yang dikirim langsung dari Pidie Jaya dan dijual di tokok-toko khusus yang menjual makanan khas Aceh. Karena proses pembuatannya tanpa memakai bahan pengawet, penganan yang teksturnya lembut dan legit ini hanya tahan paling lama empat hari.",
        "Martabak Aceh adalah makanan Aceh yang dibuat seperti bentuk martabak. Makanan ini sekilas terlihat mirip dengan telur dadar biasa. Pembuatannya sedikit berbeda dari martabak telur pada umumnya, karena kocokan telur membungkus kulit martabaknya. Pembuatan martabak ini diawali dengan menggoreng kulit martabaknya terlebih dahulu dan dibentuk segi empat, mirip dengan pembuatan roti canai. Kemudian kulit martabak dilumuri dengan kocokan telur yang telah dicampur dengan rajangan bawang merah dan daun bawang. Tahap berikutnya, kulit martabak digoreng seperti layaknya membuat dadar atau omelet, dengan kulit martabak yang berbentuk roti canai segi empat tadi sebagai intinya. \nSebagai pelengkap rasa, martabak Aceh disajikan dengan acar bawang dan cabe rawit.Martabak Aceh cukup terkenal di luar Aceh bahkan di luar daerah Aceh martabak ini dimodifikasikan dengan menggunakan gulai daging yang berbumbu kari.",
        "Mie Aceh adalah masakan mie pedas khas Aceh di Indonesia. Mie kuning tebal dengan irisan daging sapi, daging kambing atau makanan laut (udang dan cumi) disajikan dalam sup sejenis kari yang gurih dan pedas. Mie Aceh tersedia dalam tiga jenis, Mie Aceh Goreng (digoreng dan kering), Mie Aceh Tumis (dengan sedikit kuah) dan Mie Aceh Kuah (sup). Biasanya ditaburi bawang goreng dan disajikan bersama emping, potongan bawang merah, mentimun, dan jeruk nipis.",
        "Mie Jalak kalau di Jawa termasuk kategori mie kocok. Terdiri dari mie yang dimasak dengan kaldu lalu disajikan dengan topping potongan daging, tauge dan telur rebus. Katanya sih pakai kaldu ikan. Mungkin itu rahasianya sehingga tercipta kaldu bening yang gurih tapi ringan, sehingga tidak ‘eneg’ meskipun porsinya besar. Serius, porsinya kayak ngasih makan orang abis melaut seharian. Tapi karena enak, tak terasa ludes juga satu piring mie ini. Topping dagingnya gurih dan lembut, kalau kurang bisa minta ekstra daging (tentu nambah bayarnya). Sementara telur rebus merekah yang disajikan di atas mie menambah ragam rasa sepiring Mie Jalak yang dibandrol dengan harga Rp 15.000 saja. Campuran tauge yang menari di sela-sela helai mie membuat rasanya lebih segar dan renyah. Kelezatannya membuat kedai Mie Jalak populer di kalangan warga Sabang maupun pelancong.",
        "Sesuai namanya, roti jenis ini berbentuk seperti jala atau renda. Teksturnya lembut dan sedikit kenyal. Berkat bentuknya ini roti jala seolah didesain untuk menjaring kuah kari dengan maksimal ketika dicelupkan. Kuah kari yang tersaji biasanya berupa kuah ayam ataupun kambing. Benar-benar rasanya seperti pengalaman makan beragam roti khas India yang dicelup dengan berbagai sausnya yang khas!\n\nResep roti jala kuah kari ini bakalan cocok untuk berbuka puasa kamu hari ini. Menu ini bisa jadi alternatif pengganti gorengan yang berminyak ataupun gula dari makanan yang manis-manis. Roti jala dan kari ayam masih terasa ringan sebagai menu pembuka yang tidak akan membuat kamu mengantuk kalaupun kekenyangan. Sepulang Tarawih baru deh kembali untuk bersantap mie Aceh-nya. Wah, aku malah kembali obrolin menu yang satu itu lagi deh. \n\nCara membuat roti jala adalah yang pertama Campur jadi satu semua bahan roti jala hingga rata. Panaskan wajan di atas api kecil dan masak adonan menggunakan botol saus atau sendok makan hingga menyerupai bentuk jala. Masak hingga matang dan sisihkan. \n\nTumis bumbu halus hingga wangi. Masukkan juga lengkuas, serai dan daun jeruk. \n\nPadukan ayam bersama bumbu halus hingga warnanya berubah. Tambahkan santan cair dan Royco Kaldu Ayam. Masak hingga matang. \n\nSajikan roti jala dengan kari ayam. \n\nTidak hanya roti jala, paduan cocok dengan kuah kari ini bisa juga kamu terapkan dengan berbagai jenis roti lainnya. Seru sebetulnya bisa membuat berbagai bentuk roti lainnya seperti roti cane bahkan roti chapati khas India. Setelah bisa menikmati gaya makan roti yang dicelup seperti ini, pasti kamu bakalan penasaran dengan beragam sajian kuliner khas Aceh lainnya ataupun dari negara-negara tetangga kita.",
        "Berbeda dengan rujak yang biasa kita makan, rujak Aceh ini memiliki ciri khas tersendiri yang membuat rasanya berbeda dari rujak pada umumnya. Yang membuat rujak Aceh berbeda adalah buah yang dipakai. Rujak Aceh menggunakan buah rumbia khas Aceh. Buah yang daunnya digunakan untuk membuat atap rumah ini diserut bersama buah-buahan lainnya. \n\nCara membuat Rujak Aceh cukup simple pertama Masak air, cabai hingga mendidih, biarkan suhu ruang, kemudian blender bersama dengan mangga kweni, beri sejumput garam, aduk rata, koreksi rasa. lalu Potong-potong buah sesuai selera, beri saus kweni, cuka makan secukupnya, aduk rata, simpan dalam kulkas, sajikan.",
        "Sate Matang adalah tusukan daging berupa sate yang ada di provinsi Aceh. Sate ini dinamakan dengan sate matang karena awal mulanya sate ini diperkenalkan oleh penjualnya di kota Matang Geuleumpang Dua sebuah kota kecamatan di kabupaten Bireuen. \n\nPada tahun 90 an sate ini populer dibeberapa kota besar di Aceh, kini banyak sekali bertebaran penjual sate di Aceh dan kota Medan Sumatra Utara yang menjajakan sate dengan label sate matang. Bahan utama masakan sate matang adalah daging kambing, berhubung dengan harga daging kambing yang lebih mahal maka sering kali sate matang dibuat menggunakan daging sapi. \n\nProses pembuatan dan memasak sate matang tidak jauh berbeda dengan sate daerah lain di Indonesia, potongan daging yang telah dibersihkan dan dipotong dadu dalam ukuran kecil. Setelah disematkan pada tusukan sate lalu direndam dalam adonan bumbu berupa rempah-rempah dalam waktu yang agak lama. Selanjutnya sate siap untuk dibakar di pemanggangan. Sebagai pelengkap adalah kuah kaldu kambing yang khas karena taburan daun bawang, agak kental dan berasa rempah seperti masakan kari. \n\nRempah-rempah yang digunakan dalam membuat kuah kaldu ini menghasilkan aroma yang kuat, segar dan hangat. Adapun rempah yang digunakan terdiri dari kapulaga, bunga lawang, cengkih, kayu manis dan merica.",
        "Secara harfiah, sie itek memiliki arti kuah bebek. Di Aceh, hampir semua keude bu (kedai nasi) menyajikan masakan si itek ini. Bebek dengan paduan kuah kari ini punya citarasa yang lezat. Kuahnya yang kental dengan rempah lengkap jadi ciri kahs sajian bebek dari Aceh. Pedas gurih makin enak dimakan dengan pacri nanas. Walaupun lebih banyak yang sajikan sie itek dengan warna merah. Akan tetapi ada juga versi lain yang menyajikan kuah putih mirip seperti opor Jawa. \n\nSie itek yang berkuah kuning kecokelatan ini biasanya disebut dengan masak kurma walaupun dalam proses memasaknya tidak dicampur dengan kurma sebagai bumbunya. \n\nUmumnya, gulai sie itek hadir dalam dua varian yaitu : masak meurah dan masak puteh ( meubleng ). Sie itek masak meurah berkuah merah, karena salah satu bumbu utamanya ialah cabai merah. Sementara itu, sie itek masak puteh lebih mirip masakan opor. Warnanya pucat, dan tidak pedas. Beberapa orang menyebut sie itek masak puteh ini dengan masakan kurma. Mungkin karena rasanya yang tidakk pedas dan lebih gurih karena ada tambahan kemiri. \n\nKuah kari yang melumuri daging bebek terasa sangat gurih. Itu didapat dari teknik masak merebus perlahan sehingga santannya benar-benar mengental. Selain itu, masakan ini menggunakan kelapa gongseng, kelapa parut sangrai yang kemudian ditumbuk hingga berminyak. Yang pasti, rasa gurih sie itek didapat dari penggunaan 12-20 rempah yang digunakan saat memasak. \n\nDaun temurui (daun kari atau salam koja) dan daun pandan yang dipakai mengikat setiap potong bebek yang dimasak menghasilkan aroma khas. Rempah harum lain yang di pakai ialah ketumbar dan jintan. Ada dua jenis jintan yang dipakai dalam masakan ini, yaitu: jintan (cumin) dan jira ikan (fanel atau adas manis). Jira ikan merupakan jenis jintan yang sering dipakai untuk memasak ikan guna menghilangkan aroma amis atau anyir.",
        "Sie Kameng adalah Gulai Kambing Khas Aceh. Sie Kameng ini terkenal akan rasanya yang lezat karena kuah karinya yang tebal dan juga daging empuk serta bumbu rempah yang kaya rasa dan kuat. Gulai Sie Kameng ini biasanya dimasak dengan menggunakan kuali besar di depan warung makan. \n\nSie Kameng ini juga merupakan hidangan tradisional yang sering hadir dalam acara spesial di Aceh seperti acara pernikahan, acara tradisional, dan hari raya keagamaan lainnya. Dalam proses pembuatannya, Sie Kameng ini menggunakan daging kambing bertulang dan juga daging yang terpotong-potong, menggunakan rempah-rempah dan juga bumbu seperti bawang merah, bawang putih, serai, daun terumui, santan, kunyit, jahe dan juga bumbu lainnya yang semakin menguatkan kuah dari Sie Kameng ini. Gulai Si Kameng sudah menjadi makanan tradisional Aceh yang wajib bagi Sahabat Bang Johan cicipi saat berada di Aceh. Kuah kental yang kaya akan bumbu ini sangat nikmat untuk disantap karena disajikan dalam keadaan panas dan pastinya menggugah selera makan kita.",
        "Timphan adalah penganan kecil sejenis lepat yang berasal dari Aceh.Bahan untuk membuat timphan terdiri dari tepung, pisang, dan santan. Semua bahan ini kemudian diaduk-aduk sampai kenyal. Lalu dibuat memanjang dan di dalamnya diisi dengan serikaya atau kelapa parut yang dicampur dengan gula. Kemudian adonan ini dibungkus dengan daun pisang dan dikukus (rebus tanpa direndam air) selama satu jam. Timphan umumnya disajikan dalam acara-acara formal sebagai kudapan, seperti dalam pesta pernikahan dan hari-hari besar Islam. \n\nSeperti yang dijelaskan sebelumnya, Kue Timpan merupakan kue basah yang terbuat dari bahan dasar ketan dan pisang. Pisang yang digunakan biasanya adalah pisang raja, karena memiliki tekstur yang halus dan aroma yang cukup kuat. Sedangkan untuk isi Kue Timpan bisa terbuat dari parutan kelapa, pisang, ataupun srikaya. Selain itu, untuk daun pisang yang digunakan biasanya merupakan daun pisang yang masih muda. Karena selain lebih lentur, daun pisang muda juga bisa menambah aroma pada kue saat dikukus. \n\nDalam proses pembuatannya, pertama harus membuat adonan ketan dan pisang terlebih dahulu. Untuk membuatnya, santan, pisang, serta tepung ketan dimasak. Lalu tambahkan gula serta garam sedikit demi sedikit dan aduk perlahan hingga matang. Kemudian dinginkan beberapa saat. Setelah dingin, adonan tersebut lalu dipulung atau digulung menjadi satu. Kemudian setelah pembuatan adonan selesai, dilanjutkan dengan membuat isi Kue Timpan. Untuk isi parutan kelapa dan srikaya, biasanya dilakukan dengan cara yang sedikit berbeda dan sesuai dengan bahan masing masing. \n\nSetelah adonan dan isi timpan sudah siap, kemudian dilanjutkan dengan membuat Kue Timpan. Untuk membuatnya, daun pisang dibentangkan di atas telenan dan taruh satu sendok adonan ketan di atasnya. Setelah itu, beri isi timpan secukupnya, dan gulung adonan sampai isi timpan tertutup adonan. Kemudian balut adonan tersebut dengan daun pisang dan kukus hingga matang. \n\nProses pengolahan di atas hanya sedikit gambaran tentang cara pengolahan Kue Timpan. Sehingga bagi anda yang ingin membuatnya sendiri, anda bisa mencari resep yang lebih rinci dan lebih sesuai dengan keinginan anda. \n\nKue Timpan ini memiliki cita rasa yang sangat khas, perpaduan rasa manis dan gurih pada adonan ketan tentu memberikan sensasi tersendiri saat kita menyantapnya. Didukung dengan isi timpan yang terbuat dari parutan kelapa atau srikaya tentu membuat rasa Kue Timpan ini semakin nikmat. Selain itu teksturnya yang halus dan aroma pisang semakin membuat rasa Kue Timpan ini semakin komplit.",
        "Keumamah adalah salah satu kuliner tradisional masyarakat Aceh yang dibuat dari bahan baku ikan, yaitu tongkol dan cakalang[1]. Keumamah terkenal juga dengan nama ikan kayu karena keras seperti kayu. Ikan ini diawetkan dengan beberapa proses pembuatan. Mulai dari pembersihan ikan, perebusan, pengeringan dan penyimpanan. Karena itu keumamah bisa disimpan hingga bertahun-tahun dengan syarat harus tetap dalam keadaan kering atau tidak lembap. \nKeumamah hadir sebagai salah satu penganan utama yang dihidangkan saat berlangsungnya pesta adat atau kenduri. Selain memiliki peran penting dalam budaya masyarakat Aceh, keumamah juga memiliki nilai historis. Dahulu, keumamah dijadikan sebagai salah satu logistik para pejuang Aceh saat perang melawan pemerintah Kolonial Belanda. \n\nIkan tongkol yang dijadikan bahan masakan berasal dari ikan yang telah dikeringkan selama beberapa hari sehingga nyaris tidak ada lagi kandungan airnya. Sepintas teksturnya yang kering ini membuat ikan lebih mirip seperti kayu. Karena itu ikan kering ini acap disebut sebagai ikan kayu. \n\nMenurut Tengku Rusli, pemilik kedai makan di Pango Raya, Banda Aceh, ikan yang dipilih sebagai bahan keumamah harus ikan yang masih segar. Kemudian ikan tadi dibersihkan isi dalam perutnya dan dibuang bagian kepalanya. Lalu ikan direbus didalam air yang sudah ditaburi garam hingga setengah masak. \n\nKemudian ikan diangkat dari tempat perebusan memakai wadah kayu serta dikeringkan di terik matahari. Setelah kering, ikan kemudian dibelah menjadi dua bagian untuk dibuang bagian tulangnya. Tak jarang pula yang membelah ikan menjadi 3-4 bagian agar lebih mudah dalam pengerjaan pencabutan tulangnya. Kemudian dijemur kembali dengan cara diikatkan menggantung pada seutas kawat yang dibentangkan seperti tali jemuran. Ini berguna agar kandungan air semakin menetes keluar dari tubuh ikan. Proses seperti ini dilakukan sekitar tiga hari dalam kondisi terik matahari. \n\nHasilnya, membuat bobot ikan bisa berkurang hingga 70 persen dari berat ketika baru ditangkap. Tetapi jangan khawatir, cita rasa asli dari ikan tongkol yang gurih dan berlemak tetap dapat dirasakan. Ikan kayu ini diyakini mampu bertahan hingga dua tahun untuk bisa dijadikan bahan utama keumamah karena sudah direbus dalam air garam dan melalui proses pengeringan yang lama. \n\nNamun, pasokan ikan tongkol sebagai bahan utama keumamah sangat bergantung kepada ketersediaannya di laut. Ketika sedang musim, maka tak sulit untuk mendapatkan pasokan ikan tongkol. Begitu pula sebaliknya. Hal ini yang dirasakan Tengku Rusli sebagai kendala. Karena itu ia memilih untuk membuat stok ikan kayu guna menghindari kelangkaan bahan baku ikan untuk masakan keumamah.")

    private val acehFoodsImages = intArrayOf(R.drawable.asamkeueng,
        R.drawable.ayamtangkap ,
        R.drawable.bohromrom ,
        R.drawable.kuahpliek ,
        R.drawable.kueadee ,
        R.drawable.martabakaceh ,
        R.drawable.mieaceh ,
        R.drawable.miejalaksabang ,
        R.drawable.rotijala ,
        R.drawable.rujakaceh ,
        R.drawable.satematang ,
        R.drawable.sieitek ,
        R.drawable.siekameng ,
        R.drawable.timphan ,
        R.drawable.keumamah)

    val listData: ArrayList<IeNaBuNa>
        get(){
            val list = arrayListOf<IeNaBuNa>()
            for(position in acehFoodNames.indices){
                val ieNaBuNa = IeNaBuNa()
                ieNaBuNa.name = acehFoodNames[position]
                ieNaBuNa.detail = acehFoodDetails[position]
                ieNaBuNa.photo = acehFoodsImages[position]
                list.add(ieNaBuNa)
            }
            return list
        }
}